server:
 port: 8089
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/Employee
  username : root
  password : root
 mvc:
  view:
   prefix: /WEB-INF/jspPages/
   suffix: .jsp
   
   